/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { completarReporte } from '../fn/reporte-gestion-controller/completar-reporte';
import { CompletarReporte$Params } from '../fn/reporte-gestion-controller/completar-reporte';
import { createReporteGestion } from '../fn/reporte-gestion-controller/create-reporte-gestion';
import { CreateReporteGestion$Params } from '../fn/reporte-gestion-controller/create-reporte-gestion';
import { irAZona } from '../fn/reporte-gestion-controller/ir-a-zona';
import { IrAZona$Params } from '../fn/reporte-gestion-controller/ir-a-zona';
import { marcarComoResueltoPorAdmin } from '../fn/reporte-gestion-controller/marcar-como-resuelto-por-admin';
import { MarcarComoResueltoPorAdmin$Params } from '../fn/reporte-gestion-controller/marcar-como-resuelto-por-admin';
import { rechazarPorAdmin } from '../fn/reporte-gestion-controller/rechazar-por-admin';
import { RechazarPorAdmin$Params } from '../fn/reporte-gestion-controller/rechazar-por-admin';
import { ReporteGestionDto } from '../models/reporte-gestion-dto';
import { zonaUbicada } from '../fn/reporte-gestion-controller/zona-ubicada';
import { ZonaUbicada$Params } from '../fn/reporte-gestion-controller/zona-ubicada';

@Injectable({ providedIn: 'root' })
export class ReporteGestionControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `zonaUbicada()` */
  static readonly ZonaUbicadaPath = '/api/reportes/gestion/{reporteId}/zona-ubicada';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `zonaUbicada()` instead.
   *
   * This method doesn't expect any request body.
   */
  zonaUbicada$Response(params: ZonaUbicada$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteGestionDto>> {
    const obs = zonaUbicada(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `zonaUbicada$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  zonaUbicada(params: ZonaUbicada$Params, context?: HttpContext): Promise<ReporteGestionDto> {
    const resp = this.zonaUbicada$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteGestionDto>): ReporteGestionDto => r.body);
  }

  /** Path part for operation `rechazarPorAdmin()` */
  static readonly RechazarPorAdminPath = '/api/reportes/gestion/{reporteId}/rechazar-admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rechazarPorAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  rechazarPorAdmin$Response(params: RechazarPorAdmin$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteGestionDto>> {
    const obs = rechazarPorAdmin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rechazarPorAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rechazarPorAdmin(params: RechazarPorAdmin$Params, context?: HttpContext): Promise<ReporteGestionDto> {
    const resp = this.rechazarPorAdmin$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteGestionDto>): ReporteGestionDto => r.body);
  }

  /** Path part for operation `marcarComoResueltoPorAdmin()` */
  static readonly MarcarComoResueltoPorAdminPath = '/api/reportes/gestion/{reporteId}/marcar-resuelto-admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `marcarComoResueltoPorAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarComoResueltoPorAdmin$Response(params: MarcarComoResueltoPorAdmin$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteGestionDto>> {
    const obs = marcarComoResueltoPorAdmin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `marcarComoResueltoPorAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarComoResueltoPorAdmin(params: MarcarComoResueltoPorAdmin$Params, context?: HttpContext): Promise<ReporteGestionDto> {
    const resp = this.marcarComoResueltoPorAdmin$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteGestionDto>): ReporteGestionDto => r.body);
  }

  /** Path part for operation `irAZona()` */
  static readonly IrAZonaPath = '/api/reportes/gestion/{reporteId}/ir-a-zona';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `irAZona()` instead.
   *
   * This method doesn't expect any request body.
   */
  irAZona$Response(params: IrAZona$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteGestionDto>> {
    const obs = irAZona(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `irAZona$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  irAZona(params: IrAZona$Params, context?: HttpContext): Promise<ReporteGestionDto> {
    const resp = this.irAZona$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteGestionDto>): ReporteGestionDto => r.body);
  }

  /** Path part for operation `completarReporte()` */
  static readonly CompletarReportePath = '/api/reportes/gestion/{reporteId}/completar';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `completarReporte()` instead.
   *
   * This method doesn't expect any request body.
   */
  completarReporte$Response(params: CompletarReporte$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteGestionDto>> {
    const obs = completarReporte(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `completarReporte$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  completarReporte(params: CompletarReporte$Params, context?: HttpContext): Promise<ReporteGestionDto> {
    const resp = this.completarReporte$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteGestionDto>): ReporteGestionDto => r.body);
  }

  /** Path part for operation `createReporteGestion()` */
  static readonly CreateReporteGestionPath = '/api/reportes/gestion/{reporteId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createReporteGestion()` instead.
   *
   * This method doesn't expect any request body.
   */
  createReporteGestion$Response(params: CreateReporteGestion$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteGestionDto>> {
    const obs = createReporteGestion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createReporteGestion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createReporteGestion(params: CreateReporteGestion$Params, context?: HttpContext): Promise<ReporteGestionDto> {
    const resp = this.createReporteGestion$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteGestionDto>): ReporteGestionDto => r.body);
  }

}
