/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTipoIncidente } from '../fn/tipo-incidente-controller/create-tipo-incidente';
import { CreateTipoIncidente$Params } from '../fn/tipo-incidente-controller/create-tipo-incidente';
import { deleteTipoIncidente } from '../fn/tipo-incidente-controller/delete-tipo-incidente';
import { DeleteTipoIncidente$Params } from '../fn/tipo-incidente-controller/delete-tipo-incidente';
import { getAllTipoIncidentes } from '../fn/tipo-incidente-controller/get-all-tipo-incidentes';
import { GetAllTipoIncidentes$Params } from '../fn/tipo-incidente-controller/get-all-tipo-incidentes';
import { getTipoIncidenteById } from '../fn/tipo-incidente-controller/get-tipo-incidente-by-id';
import { GetTipoIncidenteById$Params } from '../fn/tipo-incidente-controller/get-tipo-incidente-by-id';
import { TipoIncidenteResponse } from '../models/tipo-incidente-response';
import { updateTipoIncidente } from '../fn/tipo-incidente-controller/update-tipo-incidente';
import { UpdateTipoIncidente$Params } from '../fn/tipo-incidente-controller/update-tipo-incidente';

@Injectable({ providedIn: 'root' })
export class TipoIncidenteControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTipoIncidenteById()` */
  static readonly GetTipoIncidenteByIdPath = '/api/tipoincidentes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTipoIncidenteById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTipoIncidenteById$Response(params: GetTipoIncidenteById$Params, context?: HttpContext): Promise<StrictHttpResponse<TipoIncidenteResponse>> {
    const obs = getTipoIncidenteById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTipoIncidenteById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTipoIncidenteById(params: GetTipoIncidenteById$Params, context?: HttpContext): Promise<TipoIncidenteResponse> {
    const resp = this.getTipoIncidenteById$Response(params, context);
    return resp.then((r: StrictHttpResponse<TipoIncidenteResponse>): TipoIncidenteResponse => r.body);
  }

  /** Path part for operation `updateTipoIncidente()` */
  static readonly UpdateTipoIncidentePath = '/api/tipoincidentes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTipoIncidente()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTipoIncidente$Response(params: UpdateTipoIncidente$Params, context?: HttpContext): Promise<StrictHttpResponse<TipoIncidenteResponse>> {
    const obs = updateTipoIncidente(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTipoIncidente$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTipoIncidente(params: UpdateTipoIncidente$Params, context?: HttpContext): Promise<TipoIncidenteResponse> {
    const resp = this.updateTipoIncidente$Response(params, context);
    return resp.then((r: StrictHttpResponse<TipoIncidenteResponse>): TipoIncidenteResponse => r.body);
  }

  /** Path part for operation `deleteTipoIncidente()` */
  static readonly DeleteTipoIncidentePath = '/api/tipoincidentes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTipoIncidente()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTipoIncidente$Response(params: DeleteTipoIncidente$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteTipoIncidente(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTipoIncidente$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTipoIncidente(params: DeleteTipoIncidente$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteTipoIncidente$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllTipoIncidentes()` */
  static readonly GetAllTipoIncidentesPath = '/api/tipoincidentes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTipoIncidentes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTipoIncidentes$Response(params?: GetAllTipoIncidentes$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TipoIncidenteResponse>>> {
    const obs = getAllTipoIncidentes(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTipoIncidentes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTipoIncidentes(params?: GetAllTipoIncidentes$Params, context?: HttpContext): Promise<Array<TipoIncidenteResponse>> {
    const resp = this.getAllTipoIncidentes$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TipoIncidenteResponse>>): Array<TipoIncidenteResponse> => r.body);
  }

  /** Path part for operation `createTipoIncidente()` */
  static readonly CreateTipoIncidentePath = '/api/tipoincidentes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTipoIncidente()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTipoIncidente$Response(params: CreateTipoIncidente$Params, context?: HttpContext): Promise<StrictHttpResponse<TipoIncidenteResponse>> {
    const obs = createTipoIncidente(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTipoIncidente$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTipoIncidente(params: CreateTipoIncidente$Params, context?: HttpContext): Promise<TipoIncidenteResponse> {
    const resp = this.createTipoIncidente$Response(params, context);
    return resp.then((r: StrictHttpResponse<TipoIncidenteResponse>): TipoIncidenteResponse => r.body);
  }

}
