/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroSeguridadDto {
  correo?: string;
  nombreCompleto?: string;
  password?: string;
  sedeId?: number;
  telefono?: string;
  username?: string;
  zonaIds?: Array<number>;
}
