/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistroUsuarioDto {
  correo?: string;
  nombreCompleto?: string;
  password?: string;
  sedeId?: number;
  telefono?: string;
  tipoUsuario?: 'ALUMNO' | 'DOCENTE';
  username?: string;
}
