/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioUpdateRequest {
  correo?: string;
  nombreCompleto?: string;
  sedeNombre?: string;
  telefono?: string;
  tipoUsuario?: 'ALUMNO' | 'DOCENTE';
  zonasNombres?: Array<string>;
}
