/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioDto {
  correo?: string;
  enabled?: boolean;
  fechaUltimoReporte?: string;
  id?: number;
  intentos?: number;
  nombreCompleto?: string;
  roles?: Array<string>;
  sedeNombre?: string;
  telefono?: string;
  tipoUsuario?: 'ALUMNO' | 'DOCENTE';
  username?: string;
  zonasNombres?: Array<string>;
}
