/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioDto } from '../../models/usuario-dto';

export interface GetFilteredSeguridadUsers$Params {
  zonaId?: number;
  sedeId?: number;
}

export function getFilteredSeguridadUsers(http: HttpClient, rootUrl: string, params?: GetFilteredSeguridadUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UsuarioDto>>> {
  const rb = new RequestBuilder(rootUrl, getFilteredSeguridadUsers.PATH, 'get');
  if (params) {
    rb.query('zonaId', params.zonaId, {});
    rb.query('sedeId', params.sedeId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UsuarioDto>>;
    })
  );
}

getFilteredSeguridadUsers.PATH = '/api/usuarios/seguridad/filter';
