/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioDto } from '../../models/usuario-dto';

export interface GetUsuarioByCodigo$Params {
  codigo: string;
}

export function getUsuarioByCodigo(http: HttpClient, rootUrl: string, params: GetUsuarioByCodigo$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioDto>> {
  const rb = new RequestBuilder(rootUrl, getUsuarioByCodigo.PATH, 'get');
  if (params) {
    rb.path('codigo', params.codigo, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioDto>;
    })
  );
}

getUsuarioByCodigo.PATH = '/api/usuarios/codigo/{codigo}';
