/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioDto } from '../../models/usuario-dto';

export interface GetUsuariosByTipoAlumno$Params {
}

export function getUsuariosByTipoAlumno(http: HttpClient, rootUrl: string, params?: GetUsuariosByTipoAlumno$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UsuarioDto>>> {
  const rb = new RequestBuilder(rootUrl, getUsuariosByTipoAlumno.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UsuarioDto>>;
    })
  );
}

getUsuariosByTipoAlumno.PATH = '/api/usuarios/tipo/alumno';
