/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioDto } from '../../models/usuario-dto';
import { UsuarioUpdateRequest } from '../../models/usuario-update-request';

export interface UpdateUsuario$Params {
  id: number;
  password?: string;
      body: UsuarioUpdateRequest
}

export function updateUsuario(http: HttpClient, rootUrl: string, params: UpdateUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioDto>> {
  const rb = new RequestBuilder(rootUrl, updateUsuario.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('password', params.password, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioDto>;
    })
  );
}

updateUsuario.PATH = '/api/usuarios/{id}';
