/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SedeRequest } from '../../models/sede-request';
import { SedeResponse } from '../../models/sede-response';

export interface CrearSede$Params {
      body: SedeRequest
}

export function crearSede(http: HttpClient, rootUrl: string, params: CrearSede$Params, context?: HttpContext): Observable<StrictHttpResponse<SedeResponse>> {
  const rb = new RequestBuilder(rootUrl, crearSede.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SedeResponse>;
    })
  );
}

crearSede.PATH = '/api/sedes';
