/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SedeResponse } from '../../models/sede-response';

export interface ListarSedes$Params {
}

export function listarSedes(http: HttpClient, rootUrl: string, params?: ListarSedes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SedeResponse>>> {
  const rb = new RequestBuilder(rootUrl, listarSedes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SedeResponse>>;
    })
  );
}

listarSedes.PATH = '/api/sedes';
