/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ZonaControllerService } from './services/zona-controller.service';
export { UsuarioControllerService } from './services/usuario-controller.service';
export { TipoIncidenteControllerService } from './services/tipo-incidente-controller.service';
export { SedeControllerService } from './services/sede-controller.service';
export { ReporteControllerService } from './services/reporte-controller.service';
export { ReporteGestionControllerService } from './services/reporte-gestion-controller.service';
export { AuthControllerService } from './services/auth-controller.service';
export { TimeControllerService } from './services/time-controller.service';
