/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { LoginDto } from './models/login-dto';
export type { RegistroAdminDto } from './models/registro-admin-dto';
export type { RegistroSeguridadDto } from './models/registro-seguridad-dto';
export type { RegistroUsuarioDto } from './models/registro-usuario-dto';
export type { ReporteDto } from './models/reporte-dto';
export type { ReporteGestionDto } from './models/reporte-gestion-dto';
export type { SedeRequest } from './models/sede-request';
export type { SedeResponse } from './models/sede-response';
export type { TipoIncidenteRequest } from './models/tipo-incidente-request';
export type { TipoIncidenteResponse } from './models/tipo-incidente-response';
export type { UsuarioDto } from './models/usuario-dto';
export type { UsuarioUpdateRequest } from './models/usuario-update-request';
export type { ZonaResponse } from './models/zona-response';
