/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteGestionDto } from '../../models/reporte-gestion-dto';

export interface CreateReporteGestion$Params {
  reporteId: number;
  estado: 'PENDIENTE' | 'EN_PROCESO' | 'UBICANDO' | 'INVESTIGANDO' | 'PENDIENTE_APROBACION' | 'RESUELTO' | 'CANCELADO';
  prioridad?: 'BAJA' | 'MEDIA' | 'ALTA';
  seguridadId?: number;
}

export function createReporteGestion(http: HttpClient, rootUrl: string, params: CreateReporteGestion$Params, context?: HttpContext): Observable<StrictHttpResponse<ReporteGestionDto>> {
  const rb = new RequestBuilder(rootUrl, createReporteGestion.PATH, 'post');
  if (params) {
    rb.path('reporteId', params.reporteId, {});
    rb.query('estado', params.estado, {});
    rb.query('prioridad', params.prioridad, {});
    rb.query('seguridadId', params.seguridadId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReporteGestionDto>;
    })
  );
}

createReporteGestion.PATH = '/api/reportes/gestion/{reporteId}';
