/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteGestionDto } from '../../models/reporte-gestion-dto';

export interface RechazarPorAdmin$Params {
  reporteId: number;
  mensajeAdmin?: string;
}

export function rechazarPorAdmin(http: HttpClient, rootUrl: string, params: RechazarPorAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<ReporteGestionDto>> {
  const rb = new RequestBuilder(rootUrl, rechazarPorAdmin.PATH, 'put');
  if (params) {
    rb.path('reporteId', params.reporteId, {});
    rb.query('mensajeAdmin', params.mensajeAdmin, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReporteGestionDto>;
    })
  );
}

rechazarPorAdmin.PATH = '/api/reportes/gestion/{reporteId}/rechazar-admin';
