/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteGestionDto } from '../../models/reporte-gestion-dto';

export interface CompletarReporte$Params {
  reporteId: number;
  mensajeSeguridad: string;
}

export function completarReporte(http: HttpClient, rootUrl: string, params: CompletarReporte$Params, context?: HttpContext): Observable<StrictHttpResponse<ReporteGestionDto>> {
  const rb = new RequestBuilder(rootUrl, completarReporte.PATH, 'put');
  if (params) {
    rb.path('reporteId', params.reporteId, {});
    rb.query('mensajeSeguridad', params.mensajeSeguridad, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReporteGestionDto>;
    })
  );
}

completarReporte.PATH = '/api/reportes/gestion/{reporteId}/completar';
