/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteDto } from '../../models/reporte-dto';

export interface CreateReporte$Params {
  tipoIncidenteId: number;
  zonaId: number;
  descripcion: string;
  isAnonimo: boolean;
  contacto?: string;
  usuarioId: number;
      body?: {
'foto'?: Blob;
}
}

export function createReporte(http: HttpClient, rootUrl: string, params: CreateReporte$Params, context?: HttpContext): Observable<StrictHttpResponse<ReporteDto>> {
  const rb = new RequestBuilder(rootUrl, createReporte.PATH, 'post');
  if (params) {
    rb.query('tipoIncidenteId', params.tipoIncidenteId, {});
    rb.query('zonaId', params.zonaId, {});
    rb.query('descripcion', params.descripcion, {});
    rb.query('isAnonimo', params.isAnonimo, {});
    rb.query('contacto', params.contacto, {});
    rb.query('usuarioId', params.usuarioId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReporteDto>;
    })
  );
}

createReporte.PATH = '/api/reportes';
