/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteDto } from '../../models/reporte-dto';

export interface GetFilteredReports$Params {
  prioridad?: 'BAJA' | 'MEDIA' | 'ALTA';
  estado?: 'PENDIENTE' | 'EN_PROCESO' | 'UBICANDO' | 'INVESTIGANDO' | 'PENDIENTE_APROBACION' | 'RESUELTO' | 'CANCELADO';
  isAnonimo?: boolean;
}

export function getFilteredReports(http: HttpClient, rootUrl: string, params?: GetFilteredReports$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReporteDto>>> {
  const rb = new RequestBuilder(rootUrl, getFilteredReports.PATH, 'get');
  if (params) {
    rb.query('prioridad', params.prioridad, {});
    rb.query('estado', params.estado, {});
    rb.query('isAnonimo', params.isAnonimo, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReporteDto>>;
    })
  );
}

getFilteredReports.PATH = '/api/reportes/filtered';
