/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteDto } from '../../models/reporte-dto';

export interface GetFilteredReportes$Params {
  zonaId?: number;
  sedeId?: number;
}

export function getFilteredReportes(http: HttpClient, rootUrl: string, params?: GetFilteredReportes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReporteDto>>> {
  const rb = new RequestBuilder(rootUrl, getFilteredReportes.PATH, 'get');
  if (params) {
    rb.query('zonaId', params.zonaId, {});
    rb.query('sedeId', params.sedeId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReporteDto>>;
    })
  );
}

getFilteredReportes.PATH = '/api/reportes/filter';
