/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteDto } from '../../models/reporte-dto';

export interface GetReporteById$Params {
  id: number;
}

export function getReporteById(http: HttpClient, rootUrl: string, params: GetReporteById$Params, context?: HttpContext): Observable<StrictHttpResponse<ReporteDto>> {
  const rb = new RequestBuilder(rootUrl, getReporteById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReporteDto>;
    })
  );
}

getReporteById.PATH = '/api/reportes/{id}';
