/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReporteDto } from '../../models/reporte-dto';

export interface GetAllReportes$Params {
}

export function getAllReportes(http: HttpClient, rootUrl: string, params?: GetAllReportes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReporteDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllReportes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReporteDto>>;
    })
  );
}

getAllReportes.PATH = '/api/reportes';
