/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { login } from '../fn/auth-controller/login';
import { Login$Params } from '../fn/auth-controller/login';
import { registrarAdmin } from '../fn/auth-controller/registrar-admin';
import { RegistrarAdmin$Params } from '../fn/auth-controller/registrar-admin';
import { registrarSeguridad } from '../fn/auth-controller/registrar-seguridad';
import { RegistrarSeguridad$Params } from '../fn/auth-controller/registrar-seguridad';
import { registrarUsuario } from '../fn/auth-controller/registrar-usuario';
import { RegistrarUsuario$Params } from '../fn/auth-controller/registrar-usuario';

@Injectable({ providedIn: 'root' })
export class AuthControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registrarUsuario()` */
  static readonly RegistrarUsuarioPath = '/api/auth/registrarUsuario';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrarUsuario()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarUsuario$Response(params: RegistrarUsuario$Params, context?: HttpContext): Promise<StrictHttpResponse<string>> {
    const obs = registrarUsuario(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrarUsuario$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarUsuario(params: RegistrarUsuario$Params, context?: HttpContext): Promise<string> {
    const resp = this.registrarUsuario$Response(params, context);
    return resp.then((r: StrictHttpResponse<string>): string => r.body);
  }

  /** Path part for operation `registrarSeguridad()` */
  static readonly RegistrarSeguridadPath = '/api/auth/registrarSeguridad';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrarSeguridad()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarSeguridad$Response(params: RegistrarSeguridad$Params, context?: HttpContext): Promise<StrictHttpResponse<string>> {
    const obs = registrarSeguridad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrarSeguridad$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarSeguridad(params: RegistrarSeguridad$Params, context?: HttpContext): Promise<string> {
    const resp = this.registrarSeguridad$Response(params, context);
    return resp.then((r: StrictHttpResponse<string>): string => r.body);
  }

  /** Path part for operation `registrarAdmin()` */
  static readonly RegistrarAdminPath = '/api/auth/registrarAdmin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrarAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarAdmin$Response(params: RegistrarAdmin$Params, context?: HttpContext): Promise<StrictHttpResponse<string>> {
    const obs = registrarAdmin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrarAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrarAdmin(params: RegistrarAdmin$Params, context?: HttpContext): Promise<string> {
    const resp = this.registrarAdmin$Response(params, context);
    return resp.then((r: StrictHttpResponse<string>): string => r.body);
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/api/auth/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Promise<StrictHttpResponse<{
}>> {
    const obs = login(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Promise<{
}> {
    const resp = this.login$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
}>): {
} => r.body);
  }

}
