/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createReporte } from '../fn/reporte-controller/create-reporte';
import { CreateReporte$Params } from '../fn/reporte-controller/create-reporte';
import { deleteReporte } from '../fn/reporte-controller/delete-reporte';
import { DeleteReporte$Params } from '../fn/reporte-controller/delete-reporte';
import { exportToExcel } from '../fn/reporte-controller/export-to-excel';
import { ExportToExcel$Params } from '../fn/reporte-controller/export-to-excel';
import { getAllReportes } from '../fn/reporte-controller/get-all-reportes';
import { GetAllReportes$Params } from '../fn/reporte-controller/get-all-reportes';
import { getFilteredReportes } from '../fn/reporte-controller/get-filtered-reportes';
import { GetFilteredReportes$Params } from '../fn/reporte-controller/get-filtered-reportes';
import { getFilteredReports } from '../fn/reporte-controller/get-filtered-reports';
import { GetFilteredReports$Params } from '../fn/reporte-controller/get-filtered-reports';
import { getReporteById } from '../fn/reporte-controller/get-reporte-by-id';
import { GetReporteById$Params } from '../fn/reporte-controller/get-reporte-by-id';
import { getReportsByUsername } from '../fn/reporte-controller/get-reports-by-username';
import { GetReportsByUsername$Params } from '../fn/reporte-controller/get-reports-by-username';
import { ReporteDto } from '../models/reporte-dto';
import { updateReporte } from '../fn/reporte-controller/update-reporte';
import { UpdateReporte$Params } from '../fn/reporte-controller/update-reporte';

@Injectable({ providedIn: 'root' })
export class ReporteControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getReporteById()` */
  static readonly GetReporteByIdPath = '/api/reportes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReporteById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReporteById$Response(params: GetReporteById$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteDto>> {
    const obs = getReporteById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReporteById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReporteById(params: GetReporteById$Params, context?: HttpContext): Promise<ReporteDto> {
    const resp = this.getReporteById$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteDto>): ReporteDto => r.body);
  }

  /** Path part for operation `updateReporte()` */
  static readonly UpdateReportePath = '/api/reportes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateReporte()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateReporte$Response(params: UpdateReporte$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteDto>> {
    const obs = updateReporte(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateReporte$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateReporte(params: UpdateReporte$Params, context?: HttpContext): Promise<ReporteDto> {
    const resp = this.updateReporte$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteDto>): ReporteDto => r.body);
  }

  /** Path part for operation `deleteReporte()` */
  static readonly DeleteReportePath = '/api/reportes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteReporte()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReporte$Response(params: DeleteReporte$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteReporte(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteReporte$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReporte(params: DeleteReporte$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteReporte$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getAllReportes()` */
  static readonly GetAllReportesPath = '/api/reportes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllReportes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReportes$Response(params?: GetAllReportes$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ReporteDto>>> {
    const obs = getAllReportes(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllReportes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReportes(params?: GetAllReportes$Params, context?: HttpContext): Promise<Array<ReporteDto>> {
    const resp = this.getAllReportes$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ReporteDto>>): Array<ReporteDto> => r.body);
  }

  /** Path part for operation `createReporte()` */
  static readonly CreateReportePath = '/api/reportes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createReporte()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReporte$Response(params: CreateReporte$Params, context?: HttpContext): Promise<StrictHttpResponse<ReporteDto>> {
    const obs = createReporte(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createReporte$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReporte(params: CreateReporte$Params, context?: HttpContext): Promise<ReporteDto> {
    const resp = this.createReporte$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReporteDto>): ReporteDto => r.body);
  }

  /** Path part for operation `getFilteredReports()` */
  static readonly GetFilteredReportsPath = '/api/reportes/filtered';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFilteredReports()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFilteredReports$Response(params?: GetFilteredReports$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ReporteDto>>> {
    const obs = getFilteredReports(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFilteredReports$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFilteredReports(params?: GetFilteredReports$Params, context?: HttpContext): Promise<Array<ReporteDto>> {
    const resp = this.getFilteredReports$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ReporteDto>>): Array<ReporteDto> => r.body);
  }

  /** Path part for operation `getFilteredReportes()` */
  static readonly GetFilteredReportesPath = '/api/reportes/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFilteredReportes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFilteredReportes$Response(params?: GetFilteredReportes$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ReporteDto>>> {
    const obs = getFilteredReportes(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFilteredReportes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFilteredReportes(params?: GetFilteredReportes$Params, context?: HttpContext): Promise<Array<ReporteDto>> {
    const resp = this.getFilteredReportes$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ReporteDto>>): Array<ReporteDto> => r.body);
  }

  /** Path part for operation `exportToExcel()` */
  static readonly ExportToExcelPath = '/api/reportes/export/excel';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `exportToExcel()` instead.
   *
   * This method doesn't expect any request body.
   */
  exportToExcel$Response(params?: ExportToExcel$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = exportToExcel(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `exportToExcel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  exportToExcel(params?: ExportToExcel$Params, context?: HttpContext): Promise<void> {
    const resp = this.exportToExcel$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `getReportsByUsername()` */
  static readonly GetReportsByUsernamePath = '/api/reportes/by-username/{username}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReportsByUsername()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportsByUsername$Response(params: GetReportsByUsername$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ReporteDto>>> {
    const obs = getReportsByUsername(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReportsByUsername$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportsByUsername(params: GetReportsByUsername$Params, context?: HttpContext): Promise<Array<ReporteDto>> {
    const resp = this.getReportsByUsername$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ReporteDto>>): Array<ReporteDto> => r.body);
  }

}
