/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { actualizarSede } from '../fn/sede-controller/actualizar-sede';
import { ActualizarSede$Params } from '../fn/sede-controller/actualizar-sede';
import { crearSede } from '../fn/sede-controller/crear-sede';
import { CrearSede$Params } from '../fn/sede-controller/crear-sede';
import { eliminarSede } from '../fn/sede-controller/eliminar-sede';
import { EliminarSede$Params } from '../fn/sede-controller/eliminar-sede';
import { listarSedes } from '../fn/sede-controller/listar-sedes';
import { ListarSedes$Params } from '../fn/sede-controller/listar-sedes';
import { obtenerSedePorId } from '../fn/sede-controller/obtener-sede-por-id';
import { ObtenerSedePorId$Params } from '../fn/sede-controller/obtener-sede-por-id';
import { SedeResponse } from '../models/sede-response';

@Injectable({ providedIn: 'root' })
export class SedeControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `obtenerSedePorId()` */
  static readonly ObtenerSedePorIdPath = '/api/sedes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `obtenerSedePorId()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerSedePorId$Response(params: ObtenerSedePorId$Params, context?: HttpContext): Promise<StrictHttpResponse<SedeResponse>> {
    const obs = obtenerSedePorId(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `obtenerSedePorId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  obtenerSedePorId(params: ObtenerSedePorId$Params, context?: HttpContext): Promise<SedeResponse> {
    const resp = this.obtenerSedePorId$Response(params, context);
    return resp.then((r: StrictHttpResponse<SedeResponse>): SedeResponse => r.body);
  }

  /** Path part for operation `actualizarSede()` */
  static readonly ActualizarSedePath = '/api/sedes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `actualizarSede()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  actualizarSede$Response(params: ActualizarSede$Params, context?: HttpContext): Promise<StrictHttpResponse<SedeResponse>> {
    const obs = actualizarSede(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `actualizarSede$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  actualizarSede(params: ActualizarSede$Params, context?: HttpContext): Promise<SedeResponse> {
    const resp = this.actualizarSede$Response(params, context);
    return resp.then((r: StrictHttpResponse<SedeResponse>): SedeResponse => r.body);
  }

  /** Path part for operation `eliminarSede()` */
  static readonly EliminarSedePath = '/api/sedes/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `eliminarSede()` instead.
   *
   * This method doesn't expect any request body.
   */
  eliminarSede$Response(params: EliminarSede$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = eliminarSede(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `eliminarSede$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  eliminarSede(params: EliminarSede$Params, context?: HttpContext): Promise<void> {
    const resp = this.eliminarSede$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `listarSedes()` */
  static readonly ListarSedesPath = '/api/sedes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarSedes()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSedes$Response(params?: ListarSedes$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<SedeResponse>>> {
    const obs = listarSedes(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarSedes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSedes(params?: ListarSedes$Params, context?: HttpContext): Promise<Array<SedeResponse>> {
    const resp = this.listarSedes$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<SedeResponse>>): Array<SedeResponse> => r.body);
  }

  /** Path part for operation `crearSede()` */
  static readonly CrearSedePath = '/api/sedes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearSede()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearSede$Response(params: CrearSede$Params, context?: HttpContext): Promise<StrictHttpResponse<SedeResponse>> {
    const obs = crearSede(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearSede$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearSede(params: CrearSede$Params, context?: HttpContext): Promise<SedeResponse> {
    const resp = this.crearSede$Response(params, context);
    return resp.then((r: StrictHttpResponse<SedeResponse>): SedeResponse => r.body);
  }

}
