/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { checkTelefonoUnique } from '../fn/usuario-controller/check-telefono-unique';
import { CheckTelefonoUnique$Params } from '../fn/usuario-controller/check-telefono-unique';
import { getAllUsersExcludingSuperAdmin } from '../fn/usuario-controller/get-all-users-excluding-super-admin';
import { GetAllUsersExcludingSuperAdmin$Params } from '../fn/usuario-controller/get-all-users-excluding-super-admin';
import { getAllUsuarios } from '../fn/usuario-controller/get-all-usuarios';
import { GetAllUsuarios$Params } from '../fn/usuario-controller/get-all-usuarios';
import { getFilteredSeguridadUsers } from '../fn/usuario-controller/get-filtered-seguridad-users';
import { GetFilteredSeguridadUsers$Params } from '../fn/usuario-controller/get-filtered-seguridad-users';
import { getUsuarioByCodigo } from '../fn/usuario-controller/get-usuario-by-codigo';
import { GetUsuarioByCodigo$Params } from '../fn/usuario-controller/get-usuario-by-codigo';
import { getUsuariosByEnabledStatus } from '../fn/usuario-controller/get-usuarios-by-enabled-status';
import { GetUsuariosByEnabledStatus$Params } from '../fn/usuario-controller/get-usuarios-by-enabled-status';
import { getUsuariosByRolAdmin } from '../fn/usuario-controller/get-usuarios-by-rol-admin';
import { GetUsuariosByRolAdmin$Params } from '../fn/usuario-controller/get-usuarios-by-rol-admin';
import { getUsuariosByRolSeguridad } from '../fn/usuario-controller/get-usuarios-by-rol-seguridad';
import { GetUsuariosByRolSeguridad$Params } from '../fn/usuario-controller/get-usuarios-by-rol-seguridad';
import { getUsuariosByRolUsuario } from '../fn/usuario-controller/get-usuarios-by-rol-usuario';
import { GetUsuariosByRolUsuario$Params } from '../fn/usuario-controller/get-usuarios-by-rol-usuario';
import { getUsuariosByTipoAlumno } from '../fn/usuario-controller/get-usuarios-by-tipo-alumno';
import { GetUsuariosByTipoAlumno$Params } from '../fn/usuario-controller/get-usuarios-by-tipo-alumno';
import { getUsuariosByTipoDocente } from '../fn/usuario-controller/get-usuarios-by-tipo-docente';
import { GetUsuariosByTipoDocente$Params } from '../fn/usuario-controller/get-usuarios-by-tipo-docente';
import { miPerfil } from '../fn/usuario-controller/mi-perfil';
import { MiPerfil$Params } from '../fn/usuario-controller/mi-perfil';
import { updateUsuario } from '../fn/usuario-controller/update-usuario';
import { UpdateUsuario$Params } from '../fn/usuario-controller/update-usuario';
import { updateUsuarioEnabledStatus } from '../fn/usuario-controller/update-usuario-enabled-status';
import { UpdateUsuarioEnabledStatus$Params } from '../fn/usuario-controller/update-usuario-enabled-status';
import { UsuarioDto } from '../models/usuario-dto';

@Injectable({ providedIn: 'root' })
export class UsuarioControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateUsuario()` */
  static readonly UpdateUsuarioPath = '/api/usuarios/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUsuario()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUsuario$Response(params: UpdateUsuario$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDto>> {
    const obs = updateUsuario(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUsuario$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUsuario(params: UpdateUsuario$Params, context?: HttpContext): Promise<UsuarioDto> {
    const resp = this.updateUsuario$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDto>): UsuarioDto => r.body);
  }

  /** Path part for operation `updateUsuarioEnabledStatus()` */
  static readonly UpdateUsuarioEnabledStatusPath = '/api/usuarios/{id}/enabled';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUsuarioEnabledStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateUsuarioEnabledStatus$Response(params: UpdateUsuarioEnabledStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDto>> {
    const obs = updateUsuarioEnabledStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUsuarioEnabledStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateUsuarioEnabledStatus(params: UpdateUsuarioEnabledStatus$Params, context?: HttpContext): Promise<UsuarioDto> {
    const resp = this.updateUsuarioEnabledStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDto>): UsuarioDto => r.body);
  }

  /** Path part for operation `getAllUsuarios()` */
  static readonly GetAllUsuariosPath = '/api/usuarios';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllUsuarios()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsuarios$Response(params?: GetAllUsuarios$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getAllUsuarios(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllUsuarios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsuarios(params?: GetAllUsuarios$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getAllUsuarios$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getUsuariosByTipoDocente()` */
  static readonly GetUsuariosByTipoDocentePath = '/api/usuarios/tipo/docente';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuariosByTipoDocente()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByTipoDocente$Response(params?: GetUsuariosByTipoDocente$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getUsuariosByTipoDocente(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuariosByTipoDocente$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByTipoDocente(params?: GetUsuariosByTipoDocente$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getUsuariosByTipoDocente$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getUsuariosByTipoAlumno()` */
  static readonly GetUsuariosByTipoAlumnoPath = '/api/usuarios/tipo/alumno';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuariosByTipoAlumno()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByTipoAlumno$Response(params?: GetUsuariosByTipoAlumno$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getUsuariosByTipoAlumno(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuariosByTipoAlumno$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByTipoAlumno(params?: GetUsuariosByTipoAlumno$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getUsuariosByTipoAlumno$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getFilteredSeguridadUsers()` */
  static readonly GetFilteredSeguridadUsersPath = '/api/usuarios/seguridad/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFilteredSeguridadUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFilteredSeguridadUsers$Response(params?: GetFilteredSeguridadUsers$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getFilteredSeguridadUsers(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFilteredSeguridadUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFilteredSeguridadUsers(params?: GetFilteredSeguridadUsers$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getFilteredSeguridadUsers$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getUsuariosByRolUsuario()` */
  static readonly GetUsuariosByRolUsuarioPath = '/api/usuarios/rol/usuario';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuariosByRolUsuario()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByRolUsuario$Response(params?: GetUsuariosByRolUsuario$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getUsuariosByRolUsuario(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuariosByRolUsuario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByRolUsuario(params?: GetUsuariosByRolUsuario$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getUsuariosByRolUsuario$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getUsuariosByRolSeguridad()` */
  static readonly GetUsuariosByRolSeguridadPath = '/api/usuarios/rol/seguridad';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuariosByRolSeguridad()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByRolSeguridad$Response(params?: GetUsuariosByRolSeguridad$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getUsuariosByRolSeguridad(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuariosByRolSeguridad$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByRolSeguridad(params?: GetUsuariosByRolSeguridad$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getUsuariosByRolSeguridad$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getUsuariosByRolAdmin()` */
  static readonly GetUsuariosByRolAdminPath = '/api/usuarios/rol/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuariosByRolAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByRolAdmin$Response(params?: GetUsuariosByRolAdmin$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getUsuariosByRolAdmin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuariosByRolAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByRolAdmin(params?: GetUsuariosByRolAdmin$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getUsuariosByRolAdmin$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `miPerfil()` */
  static readonly MiPerfilPath = '/api/usuarios/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `miPerfil()` instead.
   *
   * This method doesn't expect any request body.
   */
  miPerfil$Response(params?: MiPerfil$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDto>> {
    const obs = miPerfil(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `miPerfil$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  miPerfil(params?: MiPerfil$Params, context?: HttpContext): Promise<UsuarioDto> {
    const resp = this.miPerfil$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDto>): UsuarioDto => r.body);
  }

  /** Path part for operation `getAllUsersExcludingSuperAdmin()` */
  static readonly GetAllUsersExcludingSuperAdminPath = '/api/usuarios/excluding-superadmin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllUsersExcludingSuperAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsersExcludingSuperAdmin$Response(params?: GetAllUsersExcludingSuperAdmin$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getAllUsersExcludingSuperAdmin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllUsersExcludingSuperAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsersExcludingSuperAdmin(params?: GetAllUsersExcludingSuperAdmin$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getAllUsersExcludingSuperAdmin$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getUsuariosByEnabledStatus()` */
  static readonly GetUsuariosByEnabledStatusPath = '/api/usuarios/enabled';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuariosByEnabledStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByEnabledStatus$Response(params: GetUsuariosByEnabledStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UsuarioDto>>> {
    const obs = getUsuariosByEnabledStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuariosByEnabledStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuariosByEnabledStatus(params: GetUsuariosByEnabledStatus$Params, context?: HttpContext): Promise<Array<UsuarioDto>> {
    const resp = this.getUsuariosByEnabledStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UsuarioDto>>): Array<UsuarioDto> => r.body);
  }

  /** Path part for operation `getUsuarioByCodigo()` */
  static readonly GetUsuarioByCodigoPath = '/api/usuarios/codigo/{codigo}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuarioByCodigo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuarioByCodigo$Response(params: GetUsuarioByCodigo$Params, context?: HttpContext): Promise<StrictHttpResponse<UsuarioDto>> {
    const obs = getUsuarioByCodigo(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuarioByCodigo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuarioByCodigo(params: GetUsuarioByCodigo$Params, context?: HttpContext): Promise<UsuarioDto> {
    const resp = this.getUsuarioByCodigo$Response(params, context);
    return resp.then((r: StrictHttpResponse<UsuarioDto>): UsuarioDto => r.body);
  }

  /** Path part for operation `checkTelefonoUnique()` */
  static readonly CheckTelefonoUniquePath = '/api/usuarios/check-telefono';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkTelefonoUnique()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkTelefonoUnique$Response(params: CheckTelefonoUnique$Params, context?: HttpContext): Promise<StrictHttpResponse<boolean>> {
    const obs = checkTelefonoUnique(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkTelefonoUnique$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkTelefonoUnique(params: CheckTelefonoUnique$Params, context?: HttpContext): Promise<boolean> {
    const resp = this.checkTelefonoUnique$Response(params, context);
    return resp.then((r: StrictHttpResponse<boolean>): boolean => r.body);
  }

}
