/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { crearZona } from '../fn/zona-controller/crear-zona';
import { CrearZona$Params } from '../fn/zona-controller/crear-zona';
import { deleteZona } from '../fn/zona-controller/delete-zona';
import { DeleteZona$Params } from '../fn/zona-controller/delete-zona';
import { listarZonas } from '../fn/zona-controller/listar-zonas';
import { ListarZonas$Params } from '../fn/zona-controller/listar-zonas';
import { listarZonasPorSede } from '../fn/zona-controller/listar-zonas-por-sede';
import { ListarZonasPorSede$Params } from '../fn/zona-controller/listar-zonas-por-sede';
import { setActivoZona } from '../fn/zona-controller/set-activo-zona';
import { SetActivoZona$Params } from '../fn/zona-controller/set-activo-zona';
import { updateZona } from '../fn/zona-controller/update-zona';
import { UpdateZona$Params } from '../fn/zona-controller/update-zona';
import { ZonaResponse } from '../models/zona-response';

@Injectable({ providedIn: 'root' })
export class ZonaControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateZona()` */
  static readonly UpdateZonaPath = '/api/zonas/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateZona()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateZona$Response(params: UpdateZona$Params, context?: HttpContext): Promise<StrictHttpResponse<ZonaResponse>> {
    const obs = updateZona(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateZona$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateZona(params: UpdateZona$Params, context?: HttpContext): Promise<ZonaResponse> {
    const resp = this.updateZona$Response(params, context);
    return resp.then((r: StrictHttpResponse<ZonaResponse>): ZonaResponse => r.body);
  }

  /** Path part for operation `deleteZona()` */
  static readonly DeleteZonaPath = '/api/zonas/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteZona()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteZona$Response(params: DeleteZona$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deleteZona(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteZona$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteZona(params: DeleteZona$Params, context?: HttpContext): Promise<void> {
    const resp = this.deleteZona$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `listarZonas()` */
  static readonly ListarZonasPath = '/api/zonas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarZonas()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarZonas$Response(params?: ListarZonas$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ZonaResponse>>> {
    const obs = listarZonas(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarZonas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarZonas(params?: ListarZonas$Params, context?: HttpContext): Promise<Array<ZonaResponse>> {
    const resp = this.listarZonas$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ZonaResponse>>): Array<ZonaResponse> => r.body);
  }

  /** Path part for operation `crearZona()` */
  static readonly CrearZonaPath = '/api/zonas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `crearZona()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearZona$Response(params: CrearZona$Params, context?: HttpContext): Promise<StrictHttpResponse<ZonaResponse>> {
    const obs = crearZona(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `crearZona$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  crearZona(params: CrearZona$Params, context?: HttpContext): Promise<ZonaResponse> {
    const resp = this.crearZona$Response(params, context);
    return resp.then((r: StrictHttpResponse<ZonaResponse>): ZonaResponse => r.body);
  }

  /** Path part for operation `setActivoZona()` */
  static readonly SetActivoZonaPath = '/api/zonas/{id}/activo';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setActivoZona()` instead.
   *
   * This method doesn't expect any request body.
   */
  setActivoZona$Response(params: SetActivoZona$Params, context?: HttpContext): Promise<StrictHttpResponse<ZonaResponse>> {
    const obs = setActivoZona(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setActivoZona$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setActivoZona(params: SetActivoZona$Params, context?: HttpContext): Promise<ZonaResponse> {
    const resp = this.setActivoZona$Response(params, context);
    return resp.then((r: StrictHttpResponse<ZonaResponse>): ZonaResponse => r.body);
  }

  /** Path part for operation `listarZonasPorSede()` */
  static readonly ListarZonasPorSedePath = '/api/zonas/sede/{sedeId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarZonasPorSede()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarZonasPorSede$Response(params: ListarZonasPorSede$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ZonaResponse>>> {
    const obs = listarZonasPorSede(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarZonasPorSede$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarZonasPorSede(params: ListarZonasPorSede$Params, context?: HttpContext): Promise<Array<ZonaResponse>> {
    const resp = this.listarZonasPorSede$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ZonaResponse>>): Array<ZonaResponse> => r.body);
  }

}
