/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoIncidenteRequest } from '../../models/tipo-incidente-request';
import { TipoIncidenteResponse } from '../../models/tipo-incidente-response';

export interface CreateTipoIncidente$Params {
      body: TipoIncidenteRequest
}

export function createTipoIncidente(http: HttpClient, rootUrl: string, params: CreateTipoIncidente$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoIncidenteResponse>> {
  const rb = new RequestBuilder(rootUrl, createTipoIncidente.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoIncidenteResponse>;
    })
  );
}

createTipoIncidente.PATH = '/api/tipoincidentes';
