/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoIncidenteResponse } from '../../models/tipo-incidente-response';

export interface GetTipoIncidenteById$Params {
  id: number;
}

export function getTipoIncidenteById(http: HttpClient, rootUrl: string, params: GetTipoIncidenteById$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoIncidenteResponse>> {
  const rb = new RequestBuilder(rootUrl, getTipoIncidenteById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoIncidenteResponse>;
    })
  );
}

getTipoIncidenteById.PATH = '/api/tipoincidentes/{id}';
