/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TipoIncidenteResponse } from '../../models/tipo-incidente-response';

export interface GetAllTipoIncidentes$Params {
}

export function getAllTipoIncidentes(http: HttpClient, rootUrl: string, params?: GetAllTipoIncidentes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TipoIncidenteResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllTipoIncidentes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TipoIncidenteResponse>>;
    })
  );
}

getAllTipoIncidentes.PATH = '/api/tipoincidentes';
