/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ZonaResponse } from '../../models/zona-response';

export interface UpdateZona$Params {
  id: number;
  nombre: string;
  descripcion: string;
  sedeId: number;
      body?: {
'foto'?: Blob;
}
}

export function updateZona(http: HttpClient, rootUrl: string, params: UpdateZona$Params, context?: HttpContext): Observable<StrictHttpResponse<ZonaResponse>> {
  const rb = new RequestBuilder(rootUrl, updateZona.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('nombre', params.nombre, {});
    rb.query('descripcion', params.descripcion, {});
    rb.query('sedeId', params.sedeId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ZonaResponse>;
    })
  );
}

updateZona.PATH = '/api/zonas/{id}';
