/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ZonaResponse } from '../../models/zona-response';

export interface ListarZonas$Params {
  includeInactive?: boolean;
}

export function listarZonas(http: HttpClient, rootUrl: string, params?: ListarZonas$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ZonaResponse>>> {
  const rb = new RequestBuilder(rootUrl, listarZonas.PATH, 'get');
  if (params) {
    rb.query('includeInactive', params.includeInactive, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ZonaResponse>>;
    })
  );
}

listarZonas.PATH = '/api/zonas';
