/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ZonaResponse } from '../../models/zona-response';

export interface ListarZonasPorSede$Params {
  sedeId: number;
  includeInactive?: boolean;
}

export function listarZonasPorSede(http: HttpClient, rootUrl: string, params: ListarZonasPorSede$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ZonaResponse>>> {
  const rb = new RequestBuilder(rootUrl, listarZonasPorSede.PATH, 'get');
  if (params) {
    rb.path('sedeId', params.sedeId, {});
    rb.query('includeInactive', params.includeInactive, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ZonaResponse>>;
    })
  );
}

listarZonasPorSede.PATH = '/api/zonas/sede/{sedeId}';
